export enum ERC20Contracts {
  dLINK = "dLINK",
  dBTC = "dBTC",
  dETH = "dETH",
  dUNI = "dUNI",
  data = "data",
  PRICE_FEED = "PriceFeed",
  DAFI = "Dafi",
  wBTC = "wBTC",
  ETH = "ETH",
  ChainLINK = "LINK",
  dAAVE="dAAVE",
  AAVE="AAVE",
  DAFIPLATFORM = "DAFIPLATFORM",
}
